from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import base64
import io
import os

os.environ.setdefault('MPLCONFIGDIR', '/tmp/matplotlib')
os.makedirs(os.environ['MPLCONFIGDIR'], exist_ok=True)

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

app = FastAPI(title='Matplotlib Renderer Function')


class RenderRequest(BaseModel):
    code: str


@app.get('/')
def health():
    return {'ok': True}


@app.post('/')
def render_matplotlib(payload: RenderRequest):
    code = (payload.code or '').strip()
    if not code:
        raise HTTPException(status_code=400, detail='code is required')

    local_scope = {'plt': plt}
    safe_builtins = {
        '__import__': __import__,
        'range': range,
        'len': len,
        'min': min,
        'max': max,
        'abs': abs,
        'float': float,
        'int': int,
        'sum': sum,
    }

    try:
        exec(code, {'__builtins__': safe_builtins}, local_scope)
        fig = local_scope.get('fig') or plt.gcf()
        if fig is None:
            raise ValueError('No figure generated by code')

        buf = io.BytesIO()
        fig.savefig(buf, format='png', dpi=180, bbox_inches='tight', facecolor='white')
        buf.seek(0)
        image_data = base64.b64encode(buf.read()).decode('utf-8')
        return {'imageDataUrl': f'data:image/png;base64,{image_data}'}
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f'Failed to render matplotlib code: {exc}') from exc
    finally:
        plt.close('all')
